apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  # NOTE: In production, use stronger passwords and manage secrets with a secret manager
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  MYSQL_PASSWORD: "wordpress123"
